channels:
  - conda-forge
dependencies:
  - intake
  - intake-xarray
  - xarray
  - zarr
  - fsspec
  - s3fs
  - h5netcdf
  - matplotlib
  - holoviews
  - geoviews
  - datashader
  - hvplot
  - panel
  - requests
  - pandas
